version: '3.8'

services:
  # Development database only - app runs locally
  postgres:
    container_name: homequest-postgres-dev
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: homequest
      POSTGRES_PASSWORD: homequest123
      POSTGRES_DB: homequest_db
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - postgres-dev-data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U homequest -d homequest_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    container_name: homequest-redis-dev
    image: redis:7-alpine
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis-dev-data:/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  minio:
    container_name: homequest-minio-dev
    image: minio/minio:latest
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - minio-dev-data:/data
    command: server /data --console-address ":9001"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  createbuckets:
    image: minio/mc:latest
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      sleep 5;
      /usr/bin/mc alias set myminio http://minio:9000 minioadmin minioadmin;
      /usr/bin/mc mb myminio/homequest-uploads || true;
      /usr/bin/mc mb myminio/homequest-exports || true;
      /usr/bin/mc mb myminio/homequest-thumbnails || true;
      /usr/bin/mc anonymous set public myminio/homequest-thumbnails;
      exit 0;
      "

volumes:
  postgres-dev-data:
  redis-dev-data:
  minio-dev-data: