-- Create extensions
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- Create custom types
CREATE TYPE user_role AS ENUM ('admin', 'user', 'contractor', 'architect', 'engineer');
CREATE TYPE project_status AS ENUM ('planning', 'in_progress', 'completed', 'on_hold', 'cancelled');
CREATE TYPE project_type AS ENUM ('residential', 'commercial', 'industrial', 'infrastructure');
CREATE TYPE processing_status AS ENUM ('pending', 'processing', 'completed', 'failed', 'cancelled');

-- Users table
CREATE TABLE IF NOT EXISTS users (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
        email VARCHAR(255) UNIQUE NOT NULL,
            password_hash VARCHAR(255) NOT NULL,
                first_name VARCHAR(100) NOT NULL,
                    last_name VARCHAR(100) NOT NULL,
                        phone VARCHAR(20),
                            role user_role DEFAULT 'user',
                                is_active BOOLEAN DEFAULT true,
                                    email_verified BOOLEAN DEFAULT false,
                                        metadata JSONB DEFAULT '{}',
                                            created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
                                                updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
                                                );

                                                -- Projects table
                                                CREATE TABLE IF NOT EXISTS projects (
                                                    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
                                                        user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
                                                            name VARCHAR(255) NOT NULL,
                                                                description TEXT,
                                                                    type project_type NOT NULL,
                                                                        status project_status DEFAULT 'planning',
                                                                            address JSONB,
                                                                                coordinates JSONB,
                                                                                    start_date DATE,
                                                                                        end_date DATE,
                                                                                            budget DECIMAL(15, 2),
                                                                                                metadata JSONB DEFAULT '{}',
                                                                                                    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
                                                                                                        updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
                                                                                                        );

                                                                                                        -- Floor plans table
                                                                                                        CREATE TABLE IF NOT EXISTS floor_plans (
                                                                                                            id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
                                                                                                                project_id UUID NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
                                                                                                                    name VARCHAR(255) NOT NULL,
                                                                                                                        level INTEGER DEFAULT 0,
                                                                                                                            area DECIMAL(10, 2),
                                                                                                                                units VARCHAR(10) DEFAULT 'sqft',
                                                                                                                                    original_file_url TEXT,
                                                                                                                                        processed_file_url TEXT,
                                                                                                                                            thumbnail_url TEXT,
                                                                                                                                                processing_status processing_status DEFAULT 'pending',
                                                                                                                                                    processing_result JSONB,
                                                                                                                                                        rooms JSONB,
                                                                                                                                                            walls JSONB,
                                                                                                                                                                dimensions JSONB,
                                                                                                                                                                    metadata JSONB DEFAULT '{}',
                                                                                                                                                                        created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
                                                                                                                                                                            updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
                                                                                                                                                                                processed_at TIMESTAMP WITH TIME ZONE
                                                                                                                                                                                );

                                                                                                                                                                                -- 3D models table
                                                                                                                                                                                CREATE TABLE IF NOT EXISTS models_3d (
                                                                                                                                                                                    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
                                                                                                                                                                                        floor_plan_id UUID NOT NULL REFERENCES floor_plans(id) ON DELETE CASCADE,
                                                                                                                                                                                            format VARCHAR(20) NOT NULL,
                                                                                                                                                                                                file_url TEXT NOT NULL,
                                                                                                                                                                                                    file_size BIGINT,
                                                                                                                                                                                                        quality VARCHAR(20) DEFAULT 'medium',
                                                                                                                                                                                                            includes_textures BOOLEAN DEFAULT true,
                                                                                                                                                                                                                includes_materials BOOLEAN DEFAULT true,
                                                                                                                                                                                                                    metadata JSONB DEFAULT '{}',
                                                                                                                                                                                                                        created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
                                                                                                                                                                                                                        );

                                                                                                                                                                                                                        -- Processing jobs table
                                                                                                                                                                                                                        CREATE TABLE IF NOT EXISTS processing_jobs (
                                                                                                                                                                                                                            id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
                                                                                                                                                                                                                                floor_plan_id UUID REFERENCES floor_plans(id) ON DELETE CASCADE,
                                                                                                                                                                                                                                    job_type VARCHAR(50) NOT NULL,
                                                                                                                                                                                                                                        status processing_status DEFAULT 'pending',
                                                                                                                                                                                                                                            priority INTEGER DEFAULT 0,
                                                                                                                                                                                                                                                attempts INTEGER DEFAULT 0,
                                                                                                                                                                                                                                                    max_attempts INTEGER DEFAULT 3,
                                                                                                                                                                                                                                                        input_data JSONB,
                                                                                                                                                                                                                                                            output_data JSONB,
                                                                                                                                                                                                                                                                error_message TEXT,
                                                                                                                                                                                                                                                                    started_at TIMESTAMP WITH TIME ZONE,
                                                                                                                                                                                                                                                                        completed_at TIMESTAMP WITH TIME ZONE,
                                                                                                                                                                                                                                                                            created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
                                                                                                                                                                                                                                                                                updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
                                                                                                                                                                                                                                                                                );

                                                                                                                                                                                                                                                                                -- User sessions table
                                                                                                                                                                                                                                                                                CREATE TABLE IF NOT EXISTS user_sessions (
                                                                                                                                                                                                                                                                                    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
                                                                                                                                                                                                                                                                                        user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
                                                                                                                                                                                                                                                                                            token_hash VARCHAR(255) UNIQUE NOT NULL,
                                                                                                                                                                                                                                                                                                ip_address INET,
                                                                                                                                                                                                                                                                                                    user_agent TEXT,
                                                                                                                                                                                                                                                                                                        expires_at TIMESTAMP WITH TIME ZONE NOT NULL,
                                                                                                                                                                                                                                                                                                            created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
                                                                                                                                                                                                                                                                                                                last_activity TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
                                                                                                                                                                                                                                                                                                                );

                                                                                                                                                                                                                                                                                                                -- Audit log table
                                                                                                                                                                                                                                                                                                                CREATE TABLE IF NOT EXISTS audit_logs (
                                                                                                                                                                                                                                                                                                                    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
                                                                                                                                                                                                                                                                                                                        user_id UUID REFERENCES users(id) ON DELETE SET NULL,
                                                                                                                                                                                                                                                                                                                            action VARCHAR(100) NOT NULL,
                                                                                                                                                                                                                                                                                                                                entity_type VARCHAR(50),
                                                                                                                                                                                                                                                                                                                                    entity_id UUID,
                                                                                                                                                                                                                                                                                                                                        old_values JSONB,
                                                                                                                                                                                                                                                                                                                                            new_values JSONB,
                                                                                                                                                                                                                                                                                                                                                ip_address INET,
                                                                                                                                                                                                                                                                                                                                                    user_agent TEXT,
                                                                                                                                                                                                                                                                                                                                                        metadata JSONB DEFAULT '{}',
                                                                                                                                                                                                                                                                                                                                                            created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
                                                                                                                                                                                                                                                                                                                                                            );

                                                                                                                                                                                                                                                                                                                                                            -- Create indexes
                                                                                                                                                                                                                                                                                                                                                            CREATE INDEX idx_users_email ON users(email);
                                                                                                                                                                                                                                                                                                                                                            CREATE INDEX idx_users_role ON users(role);
                                                                                                                                                                                                                                                                                                                                                            CREATE INDEX idx_projects_user_id ON projects(user_id);
                                                                                                                                                                                                                                                                                                                                                            CREATE INDEX idx_projects_status ON projects(status);
                                                                                                                                                                                                                                                                                                                                                            CREATE INDEX idx_floor_plans_project_id ON floor_plans(project_id);
                                                                                                                                                                                                                                                                                                                                                            CREATE INDEX idx_floor_plans_processing_status ON floor_plans(processing_status);
                                                                                                                                                                                                                                                                                                                                                            CREATE INDEX idx_models_3d_floor_plan_id ON models_3d(floor_plan_id);
                                                                                                                                                                                                                                                                                                                                                            CREATE INDEX idx_processing_jobs_floor_plan_id ON processing_jobs(floor_plan_id);
                                                                                                                                                                                                                                                                                                                                                            CREATE INDEX idx_processing_jobs_status ON processing_jobs(status);
                                                                                                                                                                                                                                                                                                                                                            CREATE INDEX idx_user_sessions_user_id ON user_sessions(user_id);
                                                                                                                                                                                                                                                                                                                                                            CREATE INDEX idx_user_sessions_token_hash ON user_sessions(token_hash);
                                                                                                                                                                                                                                                                                                                                                            CREATE INDEX idx_audit_logs_user_id ON audit_logs(user_id);
                                                                                                                                                                                                                                                                                                                                                            CREATE INDEX idx_audit_logs_entity ON audit_logs(entity_type, entity_id);

                                                                                                                                                                                                                                                                                                                                                            -- Create updated_at trigger function
                                                                                                                                                                                                                                                                                                                                                            CREATE OR REPLACE FUNCTION update_updated_at_column()
                                                                                                                                                                                                                                                                                                                                                            RETURNS TRIGGER AS $$
                                                                                                                                                                                                                                                                                                                                                            BEGIN
                                                                                                                                                                                                                                                                                                                                                                NEW.updated_at = CURRENT_TIMESTAMP;
                                                                                                                                                                                                                                                                                                                                                                    RETURN NEW;
                                                                                                                                                                                                                                                                                                                                                                    END;
                                                                                                                                                                                                                                                                                                                                                                    $$ language 'plpgsql';

                                                                                                                                                                                                                                                                                                                                                                    -- Create triggers for updated_at
                                                                                                                                                                                                                                                                                                                                                                    CREATE TRIGGER update_users_updated_at BEFORE UPDATE ON users
                                                                                                                                                                                                                                                                                                                                                                        FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

                                                                                                                                                                                                                                                                                                                                                                        CREATE TRIGGER update_projects_updated_at BEFORE UPDATE ON projects
                                                                                                                                                                                                                                                                                                                                                                            FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

                                                                                                                                                                                                                                                                                                                                                                            CREATE TRIGGER update_floor_plans_updated_at BEFORE UPDATE ON floor_plans
                                                                                                                                                                                                                                                                                                                                                                                FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

                                                                                                                                                                                                                                                                                                                                                                                CREATE TRIGGER update_processing_jobs_updated_at BEFORE UPDATE ON processing_jobs
                                                                                                                                                                                                                                                                                                                                                                                    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

                                                                                                                                                                                                                                                                                                                                                                                    -- Insert default admin user (password: admin123)
                                                                                                                                                                                                                                                                                                                                                                                    INSERT INTO users (email, password_hash, first_name, last_name, role, is_active, email_verified)
                                                                                                                                                                                                                                                                                                                                                                                    VALUES (
                                                                                                                                                                                                                                                                                                                                                                                        'admin@homequest.com',
                                                                                                                                                                                                                                                                                                                                                                                            '$2a$10$YourHashedPasswordHere', -- Replace with actual bcrypt hash
                                                                                                                                                                                                                                                                                                                                                                                                'Admin',
                                                                                                                                                                                                                                                                                                                                                                                                    'User',
                                                                                                                                                                                                                                                                                                                                                                                                        'admin',
                                                                                                                                                                                                                                                                                                                                                                                                            true,
                                                                                                                                                                                                                                                                                                                                                                                                                true
                                                                                                                                                                                                                                                                                                                                                                                                                ) ON CONFLICT (email) DO NOTHING;

                                                                                                                                                                                                                                                                                                                                                                                                                -- Grant permissions
                                                                                                                                                                                                                                                                                                                                                                                                                GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO homequest;
                                                                                                                                                                                                                                                                                                                                                                                                                GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO homequest;
                                                                                                                                                                                                                                                                                                                                                                                                                GRANT ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA public TO homequest;